### ISSUE TITLE
Add congratulations to undergrads leaving

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/asmlab.org#32]
Adam, Ali, Rui, Ryan R

**Comment by aarmey** [comment]
@adamcweiner and @alifarhat30 what is the name of the specific programs you're each going to? Will update the lab website soon.

**Comment by adamcweiner** [comment]
Full name is "Tri-Institutional PhD Program in Computational Biology and Medicine" but feel free to abbreviate to "Tri-Institute CompBio" or something of the sort (https://compbio.triiprograms.org/)

**Comment by aarmey** [comment]
@rui-yan?

**Comment by alifarhat30** [comment]
-"The University of Illinois College of Medicine-Chicago Joint MD-PhD (MSTP) Program with a focus in Bioinformatics and Computational Biology at The Richard and Loan Hill Department of Bioengineering"

-Feel free to reword/abbreviate this however you like. But keep MSTP to indicate fully funded med school tuition and a yearly stipend throughout the entire duration of the program 🤑🙃😎. 

-Website if needed:
https://chicago.medicine.uic.edu/education/masters-and-doctorate-programs/medical-scientist-training-program/
