### ISSUE TITLE
Add undergrad fellowships

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/asmlab.org#38]
Adam, Ali, and Rachel’s scholarships

**Comment by alifarhat30** [comment]
Ali's scholarship: Rose Hills Foundation Fellowship
Description from their email:
"Congratulations! I am pleased to share that you have been chosen to receive the highly meritorious Rose Hills Foundation Scholarship for the 2018-19 academic year.

The Rose Hills Foundation supports the most talented and deserving students with majors in the hard sciences and engineering. You are among one of only eighteen students selected to receive this scholarship (evenly distributed throughout 3 quarters). This award will be reflected on your electronic financial aid notification prior to your fall disbursement."

**Comment by adamcweiner** [comment]
My scholarship was the "UCLA Internet Research Initiative". Here's the link to their website which includes a mission statement, a description of my proposal (on the "Prize Winners" tab), and an application portal.
